[server]
headless = true
address = "0.0.0.0"
port = 5000
enableWatchdog = false  # ðŸ‘ˆ ADD THIS LINE

[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8FF"
textColor = "#262730"
